### ISSUE TITLE
.findquote has opposite syntax to .grep

### ISSUE THREAD

**Issue by TheComet** [TheComet/GLaDOS2#35]

**Comment by Avalander** [comment]
If you haven't changed it, it only works with a mentioned user. It doesn't matter where the mention is in the content, but it needs to be a mention, it won't take a username without it. We could fix it to assume the user will be the last word in the content and work without mentions, like grep.

**Comment by TheComet** [comment]
The glados.Module base class now has a method ```parse_members_roles``` which will try to extract a list of mentioned members and roles. It also handles non-mentioned names.

If you want you can go ahead and fix this issue using this new method. Example:
```python
members, roles, error = self.parse_members_roles (message, content)
if len (members) == 0:
    error = error if error or 'No username specified'
    await self.client.send_message (message.channel, error)
    return

# members is now a list of discord.Member objects that were mentioned
```

**Comment by Avalander** [comment]
Sure, I'll give it some time tomorrow. Do you want to keep consistency with the .grep syntax, though?

**Comment by TheComet** [comment]
Since the username is an optional argument in both cases, it should be the second parameter. I.e. ```.findquote <text> [username]```. The .grep command may need to be adjusted too.

**Comment by TheComet** [comment]
Actually you know what? Hold off on this change for a sec. I didn't fully consider the requirements for parse_members_roles. I'll make some changes so you can also specify how many users or roles you want returned.

**Comment by Avalander** [comment]
Ok, I'll wait. I have to figure out how to install python 3.6 on my VPS anyway.

**Comment by TheComet** [comment]
https://github.com/TheComet/GLaDOS2/pull/65
