### ISSUE TITLE
Enable bot mods to remove messages

### ISSUE THREAD

**Issue by blueshogun96** [TheComet/GLaDOS2#37]
I believe this is a good idea for two reasons:

1. Considering that whenever a user uses the .urban command, they have no control over what is going to be displayed.  Sometimes a definition is far too inappropriate or offensive to be allowed in the chat, so it may be a good idea to allow bot mods to remove it if a server mod/admin is not there.  Furthermore, sometimes it could be accidental and could place a certain user in trouble while being unaware of a certain word's definition.  Example: cuckold

2. To help cut down on bot spam.  I understand we have the cooldown feature, but if multiple members are spamming the chat at the same time, it's still going to be a problem.

Sometimes, mods aren't always active and I'm sure they don't want to be pinged every time an inappropriate message comes up.  Just my two cents.

Shogun

**Comment by TheComet** [comment]
This feature was added in 1d4f2ad7 (bot.del.Del)
