### ISSUE TITLE
Yo Mama Jokes

### ISSUE THREAD

**Issue by ArgonianGamer** [TheComet/GLaDOS2#74]
You should make it so that GLaDOS will tell a random Yo Mama joke when you type ".yomama"

**Comment by TheComet** [comment]
The jokes could be pulled from this website: http://www.jokes4us.com/yomamajokes/random/yomama769.html

**Comment by ArgonianGamer** [comment]
That sounds good

**Comment by TheComet** [comment]
The command ```.yomama``` is now available
